[versions]
kotlin = { require = "2.3.0" }
kotest = "5.9.1"
ktlint = "1.5.0"
jvm = "17"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = { require = "7.0.2" } }

[libraries]
kotest-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-coreJvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-shared = { module = "io.kotest:kotest-assertions-shared", version.ref = "kotest" }
kotest-sharedJvm = { module = "io.kotest:kotest-assertions-shared-jvm", version.ref = "kotest" }
kotest-apiJvm = { module = "io.kotest:kotest-assertions-api-jvm", version.ref = "kotest" }

junit-bom = { module = "org.junit:junit-bom", version = { require = "5.11.4" } }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
